version = 2

songs = "*.md"

notation = "german"

[[output]]
file = "songbook.pdf"

[[output]]
file = "songbook.html"

[book]
title = "Střediskovej zpěvník"
subtitle = ""
chorus_label = "R"
title_note = "2026"
